#!/usr/bin/env python2.7

command = "diff -ubr {old_dir}/ {new_dir}/"

patch_hint = ("useage for patching: 'patch -p1 < foo.patch'\n"
              "Use this in the folder you want to patch. "
              "-p1 option tells \npatch that is already "
              "in the directory to be patched.")

usage = """Usage: %s old new patchname
Creates patch file for a complete folder structure.

%s
""" % (__file__, patch_hint,)


if __name__ == "__main__":
  import sys
  from subprocess import Popen, PIPE
  argv = sys.argv[1:]
  if len(argv) < 3:
    print "Not enough arguments"
    print usage
    sys.exit()
  old_dir = argv[0]
  new_dir = argv[1]
  patch_name = argv[2]
  command = command.format(
              old_dir=old_dir,
              new_dir=new_dir,
          )

  print "run:", command
  output = Popen(command.split(), stdout=PIPE).communicate()[0]
  with open(patch_name, 'w') as fh:
    fh.write(output)
